// Every source harvested into the tree (data/tentative and data/trusted), generated from the
// tree's README table. Counts are harvested statements; the search index drops a few
// at import (declarations with no extractable proof body).
export interface TengokuSource {
  name: string;
  repo: string;
  description: string;
  toolchain: string;
  count: number;
}

export const SOURCES: TengokuSource[] = [
  { name: "leanprover-community/mathlib4", repo: "https://github.com/leanprover-community/mathlib4", description: "the community mathematics library itself", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 188989 },
  { name: "Prove2Me", repo: "https://prove2.me", description: "collaborative Lean formalization platform; harvested via its API, each record links to the theorem's own page", toolchain: "mixed (per record)", count: 54457 },
  { name: "anthropics/fermats-last-theorem", repo: "https://github.com/anthropics/fermats-last-theorem", description: "Claude's complete, independent Lean 4 formalization of Fermat's Last Theorem (Sept 2026)", toolchain: "leanprover/lean4:v4.33.1", count: 48501 },
  { name: "CBirkbeck/AINTLIB", repo: "https://github.com/CBirkbeck/AINTLIB", description: "a monorepo aggregating several of Chris Birkbeck's own number-theory projects; only the content unique to it (ModularCurves, FltRegularBernoulli, HasseWeil, DedekindResidue, NagellLutz) is included here — the rest duplicates the standalone repos already listed", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 30131 },
  { name: "Verified-zkEVM/evm-asm", repo: "https://github.com/Verified-zkEVM/evm-asm", description: "verified EVM assembly semantics", toolchain: "leanprover/lean4:v4.33.0", count: 29092 },
  { name: "facebookresearch/atlas-lean", repo: "https://github.com/facebookresearch/atlas-lean", description: "Meta/FAIR's Atlas project", toolchain: "leanprover/lean4:v4.29.0", count: 20335 },
  { name: "frenzymath/Poincare-Conjecture", repo: "https://github.com/frenzymath/Poincare-Conjecture", description: "background lemmas toward Perelman's proof, organized by source textbook (do Carmo, Lee, Hatcher, Evans, Gilbarg–Trudinger, Chow–Knopf, Topping, Morgan–Tian, and Kleiner–Lott's exposition of Perelman's argument)", toolchain: "leanprover/lean4:v4.32.1", count: 18748 },
  { name: "teorth/equational_theories", repo: "https://github.com/teorth/equational_theories", description: "Terence Tao's project mapping relations between equational theories of magmas", toolchain: "leanprover/lean4:v4.29.1", count: 13193 },
  { name: "ColinBundschu/mass-gap", repo: "https://github.com/ColinBundschu/mass-gap", description: "Yang-Mills mass gap over compact simple groups", toolchain: "leanprover/lean4:v4.32.2", count: 11043 },
  { name: "CBirkbeck/LeanBridge", repo: "https://github.com/CBirkbeck/LeanBridge", description: "modular forms / LMFDB q-expansion computations, staged for eventual upstreaming to Mathlib (`ForMathlib/`)", toolchain: "leanprover/lean4:v4.31.0", count: 10980 },
  { name: "leanprover-community/physlib", repo: "https://github.com/leanprover-community/physlib", description: "physics results (classical mechanics, QFT, quantum info)", toolchain: "leanprover/lean4:v4.33.0", count: 10571 },
  { name: "LionSR/TNLean", repo: "https://github.com/LionSR/TNLean", description: "tensor-network theory", toolchain: "leanprover/lean4:v4.34.0-rc1", count: 10383 },
  { name: "siqiliu-tsinghua/tautology", repo: "https://github.com/siqiliu-tsinghua/tautology", description: "the reals constructed and formalized from nothing, without Mathlib", toolchain: "leanprover/lean4:v4.30.0", count: 9658 },
  { name: "Robby955/FormalSLT", repo: "https://github.com/Robby955/FormalSLT", description: "statistical learning theory (concentration, generalization bounds)", toolchain: "leanprover/lean4:v4.32.2", count: 8583 },
  { name: "AlexKontorovich/PrimeNumberTheoremAnd", repo: "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd", description: "the Prime Number Theorem and related results", toolchain: "leanprover/lean4:v4.32.2", count: 8028 },
  { name: "Verified-zkEVM/VCVio", repo: "https://github.com/Verified-zkEVM/VCVio", description: "machine-checked cryptographic proofs", toolchain: "leanprover/lean4:v4.33.1", count: 6621 },
  { name: "dwrensha/compfiles", repo: "https://github.com/dwrensha/compfiles", description: "catalog of competition problems formalized in Lean", toolchain: "leanprover/lean4:v4.34.0-rc1", count: 6042 },
  { name: "CBirkbeck/uniform-sheafy-tate-domains-lean", repo: "https://github.com/CBirkbeck/uniform-sheafy-tate-domains-lean", description: "adic spaces / uniform sheafy Tate domains (supersedes and extends Adic-Spaces below)", toolchain: "leanprover/lean4:v4.33.0", count: 5801 },
  { name: "FormalizedFormalLogic/Foundation", repo: "https://github.com/FormalizedFormalLogic/Foundation", description: "first/second-order logic completeness, Gödel's incompleteness theorems, modal logic", toolchain: "leanprover/lean4:v4.33.1", count: 5559 },
  { name: "Verified-zkEVM/CompPoly", repo: "https://github.com/Verified-zkEVM/CompPoly", description: "computable polynomial arithmetic", toolchain: "leanprover/lean4:v4.33.1", count: 4899 },
  { name: "frenzymath/FormalPantheon", repo: "https://github.com/frenzymath/FormalPantheon", description: "three named results: bounded gaps between primes, \"period three implies chaos\", and Waring's problem", toolchain: "leanprover/lean4:v4.32.0", count: 4735 },
  { name: "Verified-zkEVM/ArkLib", repo: "https://github.com/Verified-zkEVM/ArkLib", description: "formally verified arguments-of-knowledge (SNARK-adjacent) library", toolchain: "leanprover/lean4:v4.33.1", count: 4562 },
  { name: "Verified-zkEVM/PolyFun", repo: "https://github.com/Verified-zkEVM/PolyFun", description: "polynomial functional representations", toolchain: "leanprover/lean4:v4.33.1", count: 4029 },
  { name: "schildep/verified-3d-mesh-intersection", repo: "https://github.com/schildep/verified-3d-mesh-intersection", description: "formally verified 3D mesh intersection (CSG) algorithm correctness", toolchain: "leanprover/lean4:v4.15.0", count: 3753 },
  { name: "CBirkbeck/LeanModularForms", repo: "https://github.com/CBirkbeck/LeanModularForms", description: "modular forms", toolchain: "leanprover/lean4:v4.31.0-rc2", count: 3698 },
  { name: "formal-applied-math/formal-mathfin", repo: "https://github.com/formal-applied-math/formal-mathfin", description: "formally verified mathematical finance (Black-Scholes, FTAP, Merton)", toolchain: "leanprover/lean4:v4.32.0", count: 2885 },
  { name: "math-inc/Sphere-Packing-Lean", repo: "https://github.com/math-inc/Sphere-Packing-Lean", description: "sphere packing optimality in dimensions 8 and 24 (Viazovska et al.)", toolchain: "leanprover/lean4:v4.28.0", count: 2818 },
  { name: "leanprover-community/con-nf", repo: "https://github.com/leanprover-community/con-nf", description: "consistency of Quine's New Foundations set theory", toolchain: "leanprover/lean4:v4.21.0-rc3", count: 2785 },
  { name: "google-deepmind/formal-conjectures", repo: "https://github.com/google-deepmind/formal-conjectures", description: "DeepMind's formalized-conjectures benchmark (Erdős problems, Ben Green's 100 open problems, etc.); only the already-proven subset harvests here", toolchain: "leanprover/lean4:v4.33.1", count: 2584 },
  { name: "fpvandoorn/Carleson", repo: "https://github.com/fpvandoorn/Carleson", description: "Carleson's theorem on pointwise convergence of Fourier series", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 2510 },
  { name: "mortarsanjaya/IMOSLLean4", repo: "https://github.com/mortarsanjaya/IMOSLLean4", description: "IMO Shortlist problems (2006+, all categories except Geometry)", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 2330 },
  { name: "CBirkbeck/CertifyingInvariantsNF", repo: "https://github.com/CBirkbeck/CertifyingInvariantsNF", description: "certifying ideal-arithmetic invariants of number fields", toolchain: "leanprover/lean4:v4.30.0-rc1", count: 2257 },
  { name: "Lean-MoDS/StatsMLlib", repo: "https://github.com/Lean-MoDS/StatsMLlib", description: "probability/statistics/ML (concentration, empirical processes, random matrices)", toolchain: "leanprover/lean4:v4.33.0", count: 2218 },
  { name: "ImperialCollegeLondon/FLT", repo: "https://github.com/ImperialCollegeLondon/FLT", description: "Kevin Buzzard et al.'s formalization of Fermat's Last Theorem (ongoing; lemmas proven so far)", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 2198 },
  { name: "sinhp/HoTTLean", repo: "https://github.com/sinhp/HoTTLean", description: "sorry-free groupoid model of homotopy type theory", toolchain: "leanprover/lean4:v4.25.0-rc2", count: 2122 },
  { name: "leanprover-community/batteries", repo: "https://github.com/leanprover-community/batteries", description: "the community standard library (Mathlib's own foundation)", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 1960 },
  { name: "lecopivo/SciLean", repo: "https://github.com/lecopivo/SciLean", description: "scientific computing (differential equations, automatic differentiation)", toolchain: "leanprover/lean4:v4.28.0-rc1", count: 1833 },
  { name: "Verified-zkEVM/clean", repo: "https://github.com/Verified-zkEVM/clean", description: "zkVM circuit correctness", toolchain: "leanprover/lean4:v4.33.1", count: 1735 },
  { name: "YuanheZ/lean-stat-learning-theory", repo: "https://github.com/YuanheZ/lean-stat-learning-theory", description: "sorry-free statistical learning theory library", toolchain: "leanprover/lean4:v4.32.0", count: 1663 },
  { name: "teorth/IEANTN", repo: "https://github.com/teorth/IEANTN", description: "Terence Tao's analytic number theory notes/solutions", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 1522 },
  { name: "teorth/analysis", repo: "https://github.com/teorth/analysis", description: "Terence Tao's Lean companion to his \"Analysis I\" textbook", toolchain: "leanprover/lean4:v4.29.0-rc8", count: 1481 },
  { name: "RemyDegenne/brownian-motion", repo: "https://github.com/RemyDegenne/brownian-motion", description: "construction of Brownian motion, Kolmogorov–Chentsov continuity", toolchain: "leanprover/lean4:v4.33.0-rc1", count: 1441 },
  { name: "EvolvingPrograms/erdos-simonovits-degeneracy", repo: "https://github.com/EvolvingPrograms/erdos-simonovits-degeneracy", description: "machine-checked disproof of the Erdős–Simonovits degeneracy conjecture", toolchain: "leanprover/lean4:v4.32.0", count: 1435 },
  { name: "CBirkbeck/padic-L-functions", repo: "https://github.com/CBirkbeck/padic-L-functions", description: "p-adic L-functions", toolchain: "leanprover/lean4:v4.31.0-rc1", count: 1414 },
  { name: "urikol/QuantumOptimization", repo: "https://github.com/urikol/QuantumOptimization", description: "machine-verified quantum-optimization formalizations", toolchain: "leanprover/lean4:v4.28.0", count: 1400 },
  { name: "Verified-zkEVM/riscv-zkvm", repo: "https://github.com/Verified-zkEVM/riscv-zkvm", description: "RISC-V zkVM verification", toolchain: "leanprover/lean4:v4.33.0", count: 1396 },
  { name: "scottnarmstrong/DeGiorgi", repo: "https://github.com/scottnarmstrong/DeGiorgi", description: "De Giorgi–Nash–Moser elliptic PDE regularity theory", toolchain: "leanprover/lean4:v4.29.0-rc6", count: 1192 },
  { name: "uda-lab/leray-hopf", repo: "https://github.com/uda-lab/leray-hopf", description: "Leray–Hopf weak solutions for Navier–Stokes", toolchain: "leanprover/lean4:v4.31.0-rc2", count: 1151 },
  { name: "math-inc/strongpnt", repo: "https://github.com/math-inc/strongpnt", description: "the strong Prime Number Theorem, AI-formalized", toolchain: "leanprover/lean4:v4.21.0", count: 1077 },
  { name: "CBirkbeck/TauCeti", repo: "https://github.com/CBirkbeck/TauCeti", description: "the actual source of the library previously found only vendored (partially) inside `ai-safety-formalization-atlas`, now properly attributed", toolchain: "leanprover/lean4:v4.31.0", count: 1022 },
  { name: "schildep/verified-polygon-intersection", repo: "https://github.com/schildep/verified-polygon-intersection", description: "formally verified polygon intersection algorithm correctness", toolchain: "leanprover/lean4:v4.15.0", count: 942 },
  { name: "thefundamentaltheor3m/Sphere-Packing-Lean", repo: "https://github.com/thefundamentaltheor3m/Sphere-Packing-Lean", description: "sphere packing optimality in dimension 8 (the original project)", toolchain: "leanprover/lean4:v4.32.0", count: 923 },
  { name: "teorth/pfr", repo: "https://github.com/teorth/pfr", description: "Terence Tao, Yaël Dillies & Bhavik Mehta's formalization of the Polynomial Freiman-Ruzsa conjecture", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 921 },
  { name: "leanprover-community/sphere-eversion", repo: "https://github.com/leanprover-community/sphere-eversion", description: "existence of sphere eversions", toolchain: "leanprover/lean4:v4.33.0", count: 892 },
  { name: "VTrelat/ZFLean", repo: "https://github.com/VTrelat/ZFLean", description: "practical framework for set-theoretic development", toolchain: "leanprover/lean4:v4.33.0", count: 890 },
  { name: "mbrcic/ai-safety-formalization-atlas", repo: "https://github.com/mbrcic/ai-safety-formalization-atlas", description: "AI-safety-relevant claims formalized as Lean proofs", toolchain: "leanprover/lean4:v4.33.0", count: 715 },
  { name: "logical-intelligence/erdos-unit-distance", repo: "https://github.com/logical-intelligence/erdos-unit-distance", description: "a second, independent formalization of Alpöge's disproof of the Erdős unit-distance conjecture", toolchain: "leanprover/lean4:v4.29.1", count: 706 },
  { name: "teorth/sendov", repo: "https://github.com/teorth/sendov", description: "work toward Sendov's conjecture", toolchain: "leanprover/lean4:v4.34.0-rc1", count: 678 },
  { name: "Zetetic-Dhruv/formal-learning-theory-kernel", repo: "https://github.com/Zetetic-Dhruv/formal-learning-theory-kernel", description: "a kernel for synthetic formalization of statistical learning theory", toolchain: "leanprover/lean4:v4.29.0-rc6", count: 651 },
  { name: "YaelDillies/apap", repo: "https://github.com/YaelDillies/apap", description: "\"Arithmetic Progressions - Almost Periodicity\" (Kelley-Meka bound on Roth numbers)", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 622 },
  { name: "CBirkbeck/ModularForms_Lean4", repo: "https://github.com/CBirkbeck/ModularForms_Lean4", description: "modular forms (earlier project, predates LeanModularForms)", toolchain: "leanprover/lean4:v4.5.0-rc1", count: 579 },
  { name: "CBirkbeck/LocalClassFieldTheory", repo: "https://github.com/CBirkbeck/LocalClassFieldTheory", description: "local class field theory", toolchain: "leanprover/lean4:v4.7.0-rc2", count: 556 },
  { name: "trishullab/PutnamBench", repo: "https://github.com/trishullab/PutnamBench", description: "Putnam Competition (1962–2025) formalizations, Lean 4 subset", toolchain: "leanprover/lean4:v4.27.0", count: 524 },
  { name: "Ivan-Sergeyev/seymour", repo: "https://github.com/Ivan-Sergeyev/seymour", description: "Seymour's decomposition theorem for regular matroids", toolchain: "leanprover/lean4:v4.18.0", count: 468 },
  { name: "project-numina/LeanGeo", repo: "https://github.com/project-numina/LeanGeo", description: "geometry competition problems", toolchain: "leanprover/lean4:v4.15.0", count: 395 },
  { name: "WuProver/lean_characteristic_set", repo: "https://github.com/WuProver/lean_characteristic_set", description: "characteristic sets in algebraic geometry", toolchain: "leanprover/lean4:v4.29.0-rc6", count: 394 },
  { name: "djvelleman/HTPILeanPackage", repo: "https://github.com/djvelleman/HTPILeanPackage", description: "tactics and exercises for \"How to Prove It\"", toolchain: "leanprover/lean4:v4.33.0", count: 384 },
  { name: "Shreyas4991/Algolean", repo: "https://github.com/Shreyas4991/Algolean", description: "algorithms & complexity library", toolchain: "leanprover/lean4:v4.33.0", count: 364 },
  { name: "ByteDance-Seed/Seed-Prover", repo: "https://github.com/ByteDance-Seed/Seed-Prover", description: "5 of the 2025 IMO problems plus an Erdős-problem lemma battery; its vendored miniCTX-v2 copies of other libraries are excluded", toolchain: "leanprover/lean4:v4.14.0", count: 347 },
  { name: "math-inc/FrontierMathOpen-Hypergraphs", repo: "https://github.com/math-inc/FrontierMathOpen-Hypergraphs", description: "an Epoch AI FrontierMath hypergraph/Ramsey-theoretic problem", toolchain: "leanprover/lean4:v4.28.0", count: 340 },
  { name: "WuProver/groebner_proj", repo: "https://github.com/WuProver/groebner_proj", description: "Gröbner basis theory", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 327 },
  { name: "YaelDillies/ClassFieldTheory", repo: "https://github.com/YaelDillies/ClassFieldTheory", description: "2025 Clay Summer School class field theory repo", toolchain: "leanprover/lean4:v4.25.0-rc2", count: 327 },
  { name: "jsm28/AperiodicMonotilesLean", repo: "https://github.com/jsm28/AperiodicMonotilesLean", description: "the aperiodic \"hat tile\"/einstein monotile", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 311 },
  { name: "YaelDillies/mean-fourier", repo: "https://github.com/YaelDillies/mean-fourier", description: "", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 287 },
  { name: "mo271/FormalBook", repo: "https://github.com/mo271/FormalBook", description: "formalizing \"Proofs from THE BOOK\" (Aigner–Ziegler)", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 279 },
  { name: "fpvandoorn/LeanCourse24", repo: "https://github.com/fpvandoorn/LeanCourse24", description: "Floris van Doorn's Bonn Lean course, winter 2024/25", toolchain: "leanprover/lean4:v4.13.0-rc3", count: 269 },
  { name: "frenzymath/Anderson-Conjecture", repo: "https://github.com/frenzymath/Anderson-Conjecture", description: "", toolchain: "leanprover/lean4:v4.29.0-rc8", count: 263 },
  { name: "CompeteMath's own certified problems", repo: "https://competemath.com/practice/problems", description: "proofs Leak certified on this site", toolchain: "mixed (per record)", count: 262 },
  { name: "WuProver/MonomialOrderedPolynomial", repo: "https://github.com/WuProver/MonomialOrderedPolynomial", description: "monomial orderings for polynomial rings", toolchain: "leanprover/lean4:v4.29.0-rc8", count: 238 },
  { name: "ctchou/AutomataTheory", repo: "https://github.com/ctchou/AutomataTheory", description: "finite automata theory", toolchain: "leanprover/lean4:v4.24.0-rc1", count: 231 },
  { name: "frenzymath/Archon-FirstProof-Results", repo: "https://github.com/frenzymath/Archon-FirstProof-Results", description: "results from frenzymath's Archon autoformalization agent", toolchain: "leanprover/lean4:v4.28.0", count: 222 },
  { name: "teorth/estimate_tools", repo: "https://github.com/teorth/estimate_tools", description: "Terence Tao's asymptotic-estimate tooling", toolchain: "leanprover/lean4:v4.20.0-rc5", count: 221 },
  { name: "ProofOfKeags/btc-verified", repo: "https://github.com/ProofOfKeags/btc-verified", description: "verified Bitcoin protocol components", toolchain: "leanprover/lean4:v4.30.0-rc2", count: 218 },
  { name: "loganrjmurphy/LeanEuclid", repo: "https://github.com/loganrjmurphy/LeanEuclid", description: "autoformalization benchmark for Euclidean geometry", toolchain: "leanprover/lean4:v4.19.0", count: 206 },
  { name: "leanprover-community/flt-regular", repo: "https://github.com/leanprover-community/flt-regular", description: "Kummer's proof of FLT for regular primes", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 195 },
  { name: "teorth/expdb", repo: "https://github.com/teorth/expdb", description: "analytic number theory exponent database", toolchain: "leanprover/lean4:v4.32.0", count: 194 },
  { name: "b-mehta/ABC-Exceptions", repo: "https://github.com/b-mehta/ABC-Exceptions", description: "constructions of exceptions to the ABC conjecture", toolchain: "leanprover/lean4:v4.21.0-rc3", count: 192 },
  { name: "teorth/symmetric_project", repo: "https://github.com/teorth/symmetric_project", description: "", toolchain: "leanprover/lean4:v4.2.0-rc1", count: 188 },
  { name: "AnandGokhale/LeanForControl", repo: "https://github.com/AnandGokhale/LeanForControl", description: "database of control-theory proofs", toolchain: "leanprover/lean4:v4.30.0-rc2", count: 184 },
  { name: "leanprover-community/add-combi", repo: "https://github.com/leanprover-community/add-combi", description: "additive-combinatorics sublibrary", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 176 },
  { name: "a2435191/lean-logic-formalization", repo: "https://github.com/a2435191/lean-logic-formalization", description: "formalization of van den Dries's \"Logic Notes\"", toolchain: "leanprover/lean4:v4.20.0-rc5", count: 174 },
  { name: "verified-optimization/CvxLean", repo: "https://github.com/verified-optimization/CvxLean", description: "convex optimization modeling with verified correctness", toolchain: "leanprover/lean4:v4.8.0-rc1", count: 150 },
  { name: "YaelDillies/misc-yd", repo: "https://github.com/YaelDillies/misc-yd", description: "Yaël Dillies's miscellaneous results", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 138 },
  { name: "emilyriehl/infinity-cosmos", repo: "https://github.com/emilyriehl/infinity-cosmos", description: "basic formal theory of ∞-cosmoi", toolchain: "leanprover/lean4:v4.34.0-rc1", count: 134 },
  { name: "math-inc/Erdos1196", repo: "https://github.com/math-inc/Erdos1196", description: "Erdős Problem #1196 (bound on ∑1/(a·log a) for primitive sets)", toolchain: "leanprover/lean4:v4.30.0-rc1", count: 122 },
  { name: "CBirkbeck/DirichletNonvanishing", repo: "https://github.com/CBirkbeck/DirichletNonvanishing", description: "non-vanishing of Dirichlet L-functions on Re(s)=1", toolchain: "leanprover/lean4:v4.13.0-rc3", count: 118 },
  { name: "ImperialCollegeLondon/formalising-mathematics-2024", repo: "https://github.com/ImperialCollegeLondon/formalising-mathematics-2024", description: "Kevin Buzzard's Lean 4 undergraduate course, 2024", toolchain: "leanprover/lean4:v4.5.0-rc1", count: 111 },
  { name: "frenzymath/Archon-FirstProof-problem6-augmentation", repo: "https://github.com/frenzymath/Archon-FirstProof-problem6-augmentation", description: "", toolchain: "leanprover/lean4:v4.28.0", count: 108 },
  { name: "frenzymath/qrcp-bounded-coherence-obstruction", repo: "https://github.com/frenzymath/qrcp-bounded-coherence-obstruction", description: "bounded-coherence obstruction results", toolchain: "leanprover/lean4:v4.30.0-rc2", count: 103 },
  { name: "kim-em/erdos-unit-distance", repo: "https://github.com/kim-em/erdos-unit-distance", description: "Kim Morrison's formalization of Alpöge's disproof of the Erdős unit-distance conjecture", toolchain: "leanprover/lean4:v4.32.2", count: 102 },
  { name: "harmonic-ai/IMO2025", repo: "https://github.com/harmonic-ai/IMO2025", description: "Harmonic's Aristotle system, 5 of 6 IMO 2025 problems", toolchain: "leanprover/lean4:v4.20.0-rc5", count: 95 },
  { name: "YaelDillies/toric", repo: "https://github.com/YaelDillies/toric", description: "toric varieties", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 95 },
  { name: "YaelDillies/gibbs-measure", repo: "https://github.com/YaelDillies/gibbs-measure", description: "", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 94 },
  { name: "CBirkbeck/ModFormDims", repo: "https://github.com/CBirkbeck/ModFormDims", description: "dimension formulas for modular forms", toolchain: "leanprover/lean4:v4.13.0-rc3", count: 84 },
  { name: "lengyijun/goldbach_tm", repo: "https://github.com/lengyijun/goldbach_tm", description: "Goldbach conjecture encoded as a 25-state Turing machine", toolchain: "leanprover/lean4:v4.14.0-rc2", count: 83 },
  { name: "Verified-zkEVM/leanerVM", repo: "https://github.com/Verified-zkEVM/leanerVM", description: "", toolchain: "leanprover/lean4:v4.33.1", count: 81 },
  { name: "hanwenzhu/miller-rabin", repo: "https://github.com/hanwenzhu/miller-rabin", description: "Miller–Rabin primality test correctness proof", toolchain: "leanprover/lean4:v4.22.0", count: 80 },
  { name: "vltanh/lean4-analysis-tao", repo: "https://github.com/vltanh/lean4-analysis-tao", description: "formalization of Tao's \"Analysis I\"", toolchain: "leanprover/lean4:v4.29.0", count: 66 },
  { name: "CBirkbeck/NewtonPoly", repo: "https://github.com/CBirkbeck/NewtonPoly", description: "Newton polygons", toolchain: "leanprover/lean4:v4.28.0-rc1", count: 65 },
  { name: "CBirkbeck/GLn_F_q", repo: "https://github.com/CBirkbeck/GLn_F_q", description: "GL_n(F_q) representation theory", toolchain: "leanprover/lean4:v4.8.0-rc2", count: 62 },
  { name: "YaelDillies/LeanCamCombi", repo: "https://github.com/YaelDillies/LeanCamCombi", description: "Cambridge combinatorics courses", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 61 },
  { name: "YaelDillies/forbidden-matrix", repo: "https://github.com/YaelDillies/forbidden-matrix", description: "", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 60 },
  { name: "lenianiva/Prismriver", repo: "https://github.com/lenianiva/Prismriver", description: "music theory formalization + DSL", toolchain: "leanprover/lean4:v4.28.0", count: 52 },
  { name: "keilambda/ttfpi", repo: "https://github.com/keilambda/ttfpi", description: "\"Type Theory and Formal Proof: An Introduction\"", toolchain: "leanprover/lean4:v4.13.0", count: 49 },
  { name: "math-inc/RiemannHypothesisCurves", repo: "https://github.com/math-inc/RiemannHypothesisCurves", description: "the Riemann Hypothesis for curves (function-field analogue)", toolchain: "leanprover/lean4:v4.26.0-rc2", count: 49 },
  { name: "Verified-zkEVM/zkLean", repo: "https://github.com/Verified-zkEVM/zkLean", description: "", toolchain: "leanprover/lean4:v4.25.2", count: 49 },
  { name: "math-inc/ZkLinalg", repo: "https://github.com/math-inc/ZkLinalg", description: "formal security proof of Reed-Solomon IOP-of-proximity constructions", toolchain: "leanprover/lean4:v4.24.0", count: 48 },
  { name: "CBirkbeck/power_residue_symbols", repo: "https://github.com/CBirkbeck/power_residue_symbols", description: "", toolchain: "leanprover/lean4:v4.7.0-rc2", count: 44 },
  { name: "PnVDiscord/software-foundations-lean", repo: "https://github.com/PnVDiscord/software-foundations-lean", description: "\"Software Foundations\" ported to Lean 4", toolchain: "leanprover/lean4:v4.21.0", count: 37 },
  { name: "jsm28/IMOShortlist2024Lean", repo: "https://github.com/jsm28/IMOShortlist2024Lean", description: "2024 IMO Shortlist formalizations", toolchain: "leanprover/lean4:v4.22.0-rc3", count: 34 },
  { name: "CBirkbeck/chebotarev-density", repo: "https://github.com/CBirkbeck/chebotarev-density", description: "the Chebotarev density theorem", toolchain: "leanprover/lean4:v4.32.0-rc1", count: 32 },
  { name: "stepchowfun/proofs", repo: "https://github.com/stepchowfun/proofs", description: "general formally verified mathematics", toolchain: "leanprover/lean4:v4.33.1", count: 26 },
  { name: "teorth/newton", repo: "https://github.com/teorth/newton", description: "", toolchain: "leanprover/lean4:v4.5.0-rc1", count: 25 },
  { name: "teorth/equational", repo: "https://github.com/teorth/equational", description: "an earlier/smaller companion to equational_theories", toolchain: "leanprover/lean4:v4.12.0-rc1", count: 24 },
  { name: "Verified-zkEVM/ExtTreeMapLemmas", repo: "https://github.com/Verified-zkEVM/ExtTreeMapLemmas", description: "", toolchain: "leanprover/lean4:v4.29.1", count: 19 },
  { name: "ImperialCollegeLondon/IUM", repo: "https://github.com/ImperialCollegeLondon/IUM", description: "\"Introduction to University Mathematics\" course", toolchain: "leanprover/lean4:v4.17.0", count: 17 },
  { name: "MoonshotAI/CombiBench", repo: "https://github.com/MoonshotAI/CombiBench", description: "combinatorics competition benchmark", toolchain: "leanprover/lean4:v4.24.0", count: 14 },
  { name: "fpvandoorn/HausdorffSchoolLean", repo: "https://github.com/fpvandoorn/HausdorffSchoolLean", description: "Sept 2023 Hausdorff School tutorial materials, Bonn", toolchain: "leanprover/lean4:v4.0.0", count: 14 },
  { name: "optpku/CAM-Bench", repo: "https://github.com/optpku/CAM-Bench", description: "competition/applied-math proof targets", toolchain: "leanprover/lean4:v4.28.0", count: 11 },
  { name: "T-Brick/lean-wasm", repo: "https://github.com/T-Brick/lean-wasm", description: "formalization of the WebAssembly spec", toolchain: "leanprover/lean4:v4.25.0", count: 11 },
  { name: "frenzymath/reap", repo: "https://github.com/frenzymath/reap", description: "", toolchain: "leanprover/lean4:v4.28.0-rc1", count: 11 },
  { name: "frenzymath/jixia", repo: "https://github.com/frenzymath/jixia", description: "", toolchain: "leanprover/lean4:v4.29.0", count: 10 },
  { name: "YaelDillies/chandra-furst-lipton", repo: "https://github.com/YaelDillies/chandra-furst-lipton", description: "corner-free sets / communication complexity", toolchain: "leanprover/lean4:v4.34.0-rc2", count: 10 },
  { name: "math-inc/KakeyaFiniteFields", repo: "https://github.com/math-inc/KakeyaFiniteFields", description: "the Kakeya set problem over finite fields", toolchain: "leanprover/lean4:v4.26.0-rc2", count: 9 },
  { name: "WuProver/GroebnerTactic", repo: "https://github.com/WuProver/GroebnerTactic", description: "", toolchain: "leanprover/lean4:v4.29.0-rc8", count: 8 },
  { name: "shetzl/autth", repo: "https://github.com/shetzl/autth", description: "finite automata and context-free grammars", toolchain: "leanprover/lean4:v4.12.0-rc1", count: 3 },
  { name: "frenzymath/interactive", repo: "https://github.com/frenzymath/interactive", description: "", toolchain: "leanprover/lean4:v4.16.0", count: 1 },
];
